export const dishMenu = [
  { key: 1, name: "麻辣香锅" },
  { key: 2, name: "小酥肉" },
  { key: 3, name: "咖喱土豆饭" },
  { key: 4, name: "炒天津白" },
  { key: 5, name: "清炒花菜" },
  { key: 6, name: "黄焖鸡 + 小啊伟洗碗" },
  { key: 7, name: "火锅" },
  { key: 8, name: "青菜瘦肉粥" },
  { key: 9, name: "炸平菇" },
  { key: 10, name: "西红柿鸡蛋面" },
  { key: 11, name: "肉末茄子" },
  { key: 12, name: "炖排骨" },
  { key: 13, name: "炖猪蹄 + 小啊伟洗碗" },
  { key: 14, name: "炒香干" },
  { key: 15, name: "蛋炒饭" },
  { key: 16, name: "荷包蛋" },
]