name: 打包应用并上传阿里云

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@master

      - name: 安装 node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.0.0

      - name: 安装依赖
        run: npm install

      - name: 打包
        run: npm run build

      - name: 发布到阿里云
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.FYZS_PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录
          SOURCE: "dist"
          # 服务器ip
          REMOTE_HOST: "8.136.158.41"
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/usr/local/nginx/html"
